/**
* author: Lei Yang, Chenfan Zhuang
* update: Huarong Chen
*/
popushlang.install('en-US', {
		'popush-title'			:'Popush - Happy Coding!',
		'popush-brand'			:'Popush',
		'hide-title'                    :'Hide',
		'show-title'                    :'Show',
		'pleaseinput'                   :'Please input username.',
		'unauthorized'                  :'Your username and password didn\'t match. Please try again.',
		'doesntmatch'                   :'Password doesn\'t match the confirmation!',
		'namelength'                    :'The length of username must be between 6 and 20.',
		'passlength'                    :'The length of password must be less than 32.',
		'registerok'                    :'Success! please <a href="javascript:;" onclick="loginview()">log in</a>.',
		'name exists'                   :'The username already exists.',
		'inner error'                   :'Internal server error!',
		'name invalid'                  :'The username can only consists of numbers and letters.',
		'loadfailed'                    :'Unable to connect to server.',
		'inputfilename'                 :'Please enter the file name.',
		'conflict'                      :'File already exists.',
		'newfile'                       :'New File',
		'newfolder'                     :'New Folder',
		'inputpass'                     :'Please enter password.',
		'password incorrect'            :'Old password is incorrect.',
		'createfilesuccess'             :'Create a file successfully.',
		'createfoldersuccess'           :'Create a folder successfully.',
		'changepassword'                :'Change password',
		'changepassworddone'            :'Change password successfully.',
		'changeavatar'                  :'Change avatar',
		'error'                         :'Error',
		'filenameinvalid'               :'The filename cannot include / \\ @',
		'delete'                        :'Delete',
		'rename'                        :'Rename',
		'needrelogin'                   :'Need to re-login.',
		'inputusername'                 :'Please input username.',
		'selectuser'                    :'Please select a user.',
		'member already exists'         :'The user already exists in the list.',
		'member doesn\'t exists'        :'The user does not exist.',
		'file exists'                   :'File already exists.',
		'can\'t add yourself'           :'Files can not be shared with the owner.',
		'changeavatarok'                :'Change avatar successfully.',
		'openeditor'                    :'Edit',
		'systemmessage'                 :'System message',
		'join'                          :'join the room',
		'leave'                         :'leave the room',
		'console'                       :'Console',
		'\'s'                           :'\'s',
		'runsaprogram'                  :'run the program',
		'programfinish'                 :'The program has finished. Returned',
		'kill-title'                    :'Stop',
		'run-title'                     :'Run',
		'programkilledby'               :'The program has been stopped by ',
		'not supported'                 :'Unsupported type',
		'saving...'                     :'Saving...',
		'saved'                         :'Saved',
		'unsaved'                       :'The current file is not saved. Exit may cause data loss.',
		'unshared'                      :'lose the share right of the file.',
		'you unshared'                  :'You have lost the share right of the file.',
		'deleted'                       :'The file has been deleted.',
		'info'                          :'Info',
		'gotshared'                     :'obtain the share right of the file',
		'movedto'                       :'The file name is modified to ',
		'filename'                      :'Filename',
		'state'                         :'State',
		'timestamp'                     :'Last Modified',
		'nofile'                        :'No file.',
		'owner'                         :'Owner',
		'shared'                        :'Shared',
		'sharemanage'                   :'Share Management',
		'export'                        :'Export',
		'import'                        :'Import',
		'file'                          :'file',
		'folder'                        :'folder',
		'login'                         :'LOG IN',
		'username'                      :'Username',
		'password'                      :'Password',
		'register'                      :'SIGN UP',
		'logout'                        :'Log out',
		'confirm'                       :'Confirm password',
		'owningfiles'                   :'Owned files',
		'sharedfiles'                   :'Shared files',
		'currentdir:'                   :'Current directory: ',
		'shareduser'                    :'Shared with',
		'maximum-title'                 :'Full screen',
		'back'                          :'Back',
		'send'                          :'Send',
		'popushteam'                    :'Powered by popush team.',
		'ok'                            :'OK',
		'cancel'                        :'Cancel',
		'name'                          :'Name',
		'clicktochange'                 :'Click image to change avatar(support jpg，png format):',
		'add'                           :'Add',
		'newuser:'                      :'New user: ',
		'sshareduser'                   :'Shared with users: ',
		'oldpassword'                   :'Old password',
		'newpassword'                   :'New password',
		'deleteconfirm'                 :'Confirm deletion',
		'suretodelete'                  :'Do you really want to remove the ',
		'newname'                       :'New name',
		'debug-title'                   :'Debug',
		'stop-debug-title'              :'stop debugging',
		'startdebug'                    :'start debugging',
		'filenamelength'                :'The length of file name must be less than 32.',
		'addexpression'                 :'Add watch',
		'console'                       :'Console',
		'step-title'                    :'Step into',
		'next-title'                    :'Step over',
		'continue-title'                :'Continue',
		'finished'                      :'&lt;Finished&gt;',
		'waiting'                       :'&lt;Waiting&gt;',
		'nosource'                      :'&lt;Breakpoint is not in the source code&gt;',
		'too large'                     :'The size of avatar must be smaller than 1 MB.',
		'esctoexit'                     :'Press Esc to restore.',
		'finish-title'                  :'Step return',
		'voice'                         :'Voice',
		'removeexpression'              :'Remove watch',
		'novoice'                       :'The browser does not support voice. Please use Chrome 18+ or Opera 12+',
		'username-help'			:'The username can only consists of number and letter. The length of username should be between 6 and 20.',
		'password-help'			:'The length of password must be less than 32.',
		'renterpassword'		:'Please enter your password again.',
		'changeskin'			:'Change skin',
		'clicktochoose'			:'Click image to change the skin.',
		'changelanguage'		:'Change language',
		'language'			:'Language'
	});
